### ISSUE TITLE
Upgrade to python 3.5.2

### ISSUE THREAD

**Issue by davinod** [rdegges/skele-cli#2]
This sample is not compatible with Python 3.5.2, although it says that it is supposed to work in this version.

I was only able to have it working in 2.7.8 or lower versions.

Can you please ensure the code is compatible with more recent versions ?

This is the error when running with 3.5.2:

f45c899af327:skele-cli davidiog$ skele -h
Traceback (most recent call last):
  File "/Users/davidiog/.pyenv/versions/3.5.2/bin/skele", line 9, in <module>
    load_entry_point('skele', 'console_scripts', 'skele')()
  File "/Users/davidiog/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/davidiog/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/**init**.py", line 2569, in load_entry_point
    return ep.load()
  File "/Users/davidiog/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/**init**.py", line 2229, in load
    return self.resolve()
  File "/Users/davidiog/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/**init**.py", line 2235, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/davidiog/.pyenv/versions/3.5.2/lib/python3.5/site-packages/skele-1.0.0-py3.5.egg/skele/cli.py", line 38, in <module>
NameError: name 'command' is not defined

**Comment by rdegges** [comment]
This is now fixed, thanks for a generous PR!
